bullseye has been EOL
```
 INFO :   execute[apt-get update] executed will change from 'false' to 'true'
ERROR :     stdout | Get:1 http://deb.debian.org/debian bullseye InRelease [75.1 kB]
ERROR :     stdout | Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [27.2 kB]
ERROR :     stdout | Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.0 kB]
ERROR :     stdout | Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8066 kB]
ERROR :     stdout | Get:5 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [18.8 kB]
ERROR :     stdout | Reading package lists...
ERROR :     stderr | E: Release file for http://deb.debian.org/debian-security/dists/bullseye-security/InRelease is expired (invalid since 3d 16h 47min 8s). Updates for this repository will not be applied.
ERROR :     Command `apt-get update` failed. (exit status: 100)
ERROR :   execute[apt-get update] Failed.
Error: Process completed with exit code 2.
```

Close #78